### ISSUE TITLE
Action fails on npm v9

### ISSUE THREAD

**Issue by zapteryx** [EPMatt/reviewdog-action-tsc#157] opened 2023-02-24 08:40 UTC
Hey there!
Your action is failing on npm v9 (https://github.com/ZPTXDev/Skeleton/actions/runs/4260689937/jobs/7414136107).
I believe it's the same issue `creyD/prettier_action` faced (https://github.com/creyD/prettier_action/issues/113).
Hopefully this helps you to solve the issue. Thanks!

**Comment by EPMatt** [comment] 2023-03-06 15:51
Hi @zapteryx,
thank you so much for reporting here. 

The issue is due to the removal of npm bin starting from npm version 9.
The same problem affected my other reviewdog-based action: https://github.com/EPMatt/reviewdog-action-prettier/issues/34

I've just published v1.4.1, which includes a fix for this issue.
If the problem persists, please don't hesitate to open a new ticket.

Thank you so much!

**Closed** 2023-03-06 15:51 UTC

**Comment by rnovacek** [comment] 2023-03-07 11:08
Thank you for the fix. It's working great!
